# Generated by Django 3.1 on 2021-02-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210208_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
